name: NestJS CI/CD

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install webpack-cli
        run: npm install -D webpack-cli

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Run npm audit
        run: npm audit --audit-level=high || true

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test || true
